export default {
  payload: [
    {
      product_id: "CBD19S",
      description: "Cartera Batman Snap Batman Day 2019",
      brand_id: 823,
      brand: "Fantastico",
      line_id: "B",
      line: "Back Issue",
      control: "1936",
      price: "0.01",
      total_items: "3",
    },
    {
      product_id: "D15101808",
      description: "One Piece 3 In 1 TP Vol 14",
      brand_id: 2520,
      brand: "Viz Media Llc",
      line_id: "K",
      line: "Novela Seriada",
      control: "1548",
      price: "345.00",
      total_items: "1",
    },
    {
      product_id: "D19050703",
      description: "Powers Of X #1",
      brand_id: 2309,
      brand: "Marvel Comics",
      line_id: "B",
      line: "Back Issue",
      control: "1931",
      price: "132.00",
      total_items: "1",
    },
    {
      product_id: "D21060009",
      description: "Echolands #1 Cvr A Williams III",
      brand_id: 2304,
      brand: "Image Comics",
      line_id: "B",
      line: "Back Issue",
      control: "2134",
      price: "110.00",
      total_items: "1",
    },
    {
      product_id: "D21060057",
      description: "Second Chances #1",
      brand_id: 2304,
      brand: "Image Comics",
      line_id: "B",
      line: "Back Issue",
      control: "2133",
      price: "88.00",
      total_items: "1",
    },
    {
      product_id: "D21060542",
      description: "Kang The Conqueror #1",
      brand_id: 2309,
      brand: "Marvel Comics",
      line_id: "B",
      line: "Back Issue",
      control: "2133",
      price: "110.00",
      total_items: "1",
    },
    {
      product_id: "D21060629",
      description: "Moon Knight 7th Series #2",
      brand_id: 2309,
      brand: "Marvel Comics",
      line_id: "B",
      line: "Back Issue",
      control: "2133",
      price: "88.00",
      total_items: "2",
    },
    {
      product_id: "D21060642",
      description: "X-Corp #4",
      brand_id: 2309,
      brand: "Marvel Comics",
      line_id: "B",
      line: "Back Issue",
      control: "2133",
      price: "88.00",
      total_items: "1",
    },
    {
      product_id: "D21060666",
      description: "Black Cat 3rd Series #9",
      brand_id: 2309,
      brand: "Marvel Comics",
      line_id: "B",
      line: "Back Issue",
      control: "2133",
      price: "88.00",
      total_items: "1",
    },
    {
      product_id: "D21060686",
      description: "Gamma Flight #3",
      brand_id: 2309,
      brand: "Marvel Comics",
      line_id: "B",
      line: "Back Issue",
      control: "2133",
      price: "88.00",
      total_items: "1",
    },
  ],
};
